
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.ebssas.wsrestapicoopedac.deceval.sdl.services;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2017-09-19T12:15:59.417-05:00
 * Generated source version: 3.0.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "SDLService",
                      portName = "SDLServicePort",
                      targetNamespace = "http://deceval.com/sdl/services/",
                      wsdlLocation = "file:/D:/WORKSPACES/DECEVAL/WSCLIENTES/ClientSWSPagares/WebContent/WEB-INF/wsdl/SDLService.wsdl",
                      endpointInterface = "SDLService")
                      
public class SDLServicePortImpl implements SDLService {

    private static final Logger LOG = Logger.getLogger(SDLServicePortImpl.class.getName());

    /* (non-Javadoc)
     * @see SDLService#creacionPagaresFisicosCodificado(SolicitudCrearPagareDaneServiceDTO creacionPagaresFisicosCodificado)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareDaneServiceDTO creacionPagaresFisicosCodificado(SolicitudCrearPagareDaneServiceDTO creacionPagaresFisicosCodificado) { 
        LOG.info("Executing operation creacionPagaresFisicosCodificado");
        System.out.println(creacionPagaresFisicosCodificado);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareDaneServiceDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareDaneServiceDTO();
            _return.setCodigoError("CodigoError-1639627008");
            _return.setDescripcion("Descripcion1087328207");
            _return.setExitoso(Boolean.valueOf(false));
            DocumentoPagareDaneServiceDTO _returnRespuesta = new DocumentoPagareDaneServiceDTO();
            _returnRespuesta.setAdquisicionVivienda(Boolean.valueOf(false));
            _returnRespuesta.setApoderadoCuenta(Integer.valueOf(1135447357));
            _returnRespuesta.setApoderadoNumId("ApoderadoNumId-89035555");
            _returnRespuesta.setApoderadoTipoId(Integer.valueOf(-1787038994));
            java.util.List<ArchivoAdjuntoDTO> _returnRespuestaArchivosAdjuntos = new java.util.ArrayList<ArchivoAdjuntoDTO>();
            ArchivoAdjuntoDTO _returnRespuestaArchivosAdjuntosVal1 = new ArchivoAdjuntoDTO();
            _returnRespuestaArchivosAdjuntosVal1.setContenido("Contenido-651771178");
            _returnRespuestaArchivosAdjuntosVal1.setNombreArchivo("NombreArchivo1531470094");
            _returnRespuestaArchivosAdjuntos.add(_returnRespuestaArchivosAdjuntosVal1);
            _returnRespuesta.getArchivosAdjuntos().addAll(_returnRespuestaArchivosAdjuntos);
            _returnRespuesta.setAutorizaDebitoAutomatico(Boolean.valueOf(true));
            _returnRespuesta.setAval(new java.math.BigDecimal("3516576635611458161.1085849325982467470"));
            _returnRespuesta.setBaseLiquidacionPlazo("BaseLiquidacionPlazo214595763");
            _returnRespuesta.setBaseLiquidacionTasa("BaseLiquidacionTasa966587000");
            _returnRespuesta.setCiCEApartirDelMes(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.423-05:00"));
            _returnRespuesta.setCiCEPagaderaCada(Integer.valueOf(116595956));
            _returnRespuesta.setCiConCuotasExtras(Boolean.valueOf(true));
            _returnRespuesta.setCiConPeriodoGracia(Boolean.valueOf(false));
            _returnRespuesta.setCiNumCuotasExtras(Integer.valueOf(228754102));
            _returnRespuesta.setCiValorCuotaExtra(new java.math.BigDecimal("4706194279611987360.95112066430786252"));
            _returnRespuesta.setCiudadCreacion("CiudadCreacion864242236");
            _returnRespuesta.setCiudadDesembolso("CiudadDesembolso1010716891");
            _returnRespuesta.setCodOficina("CodOficina655865035");
            _returnRespuesta.setCodigoGeoreferenciacion("CodigoGeoreferenciacion1558414779");
            _returnRespuesta.setConstruccionViviendaIndividual(Boolean.valueOf(true));
            _returnRespuesta.setCreditoReembolsableEn("CreditoReembolsableEn-254048094");
            _returnRespuesta.setCuenta("Cuenta-469930669");
            _returnRespuesta.setDepartamento("Departamento1389045142");
            _returnRespuesta.setDeptoCreacion("DeptoCreacion-118119198");
            _returnRespuesta.setDestinoOperacion("DestinoOperacion-210852584");
            _returnRespuesta.setDiaPago(Integer.valueOf(205069061));
            _returnRespuesta.setDtfDessembolso(new java.math.BigDecimal("-4292273926477827040.4542550673724980618"));
            _returnRespuesta.setDtfEA("DtfEA-442623892");
            _returnRespuesta.setEmpresaOtorgante("EmpresaOtorgante2055434198");
            _returnRespuesta.setFechaDesembolso(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.423-05:00"));
            _returnRespuesta.setFechaFirmaFisico(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.423-05:00"));
            _returnRespuesta.setFechaGrabacionPagare(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.423-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuota(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.424-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuotaCapital(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.424-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuotaInteres(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.424-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuotaMensual(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.424-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuotaSemestral(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.424-05:00"));
            _returnRespuesta.setFechaVencimientoFinanciero(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.424-05:00"));
            _returnRespuesta.setGarantiaAdicional("GarantiaAdicional-790341259");
            _returnRespuesta.setIdClaseDefinicionDocumento(Long.valueOf(2564662515657545466l));
            _returnRespuesta.setIdDocumentoPagare(Long.valueOf(5288793249839909984l));
            _returnRespuesta.setIdGestorDocumental("IdGestorDocumental-1378566878");
            _returnRespuesta.setListaAmortizaciones("ListaAmortizaciones-843972278");
            java.util.List<ConsultaGiradorServiceDTO> _returnRespuestaListaApoderadoRepresentantePagare = new java.util.ArrayList<ConsultaGiradorServiceDTO>();
            ConsultaGiradorServiceDTO _returnRespuestaListaApoderadoRepresentantePagareVal1 = new ConsultaGiradorServiceDTO();
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setGiradorCuenta(Integer.valueOf(-213328002));
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setGiradorNumId("GiradorNumId104309899");
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setGiradorTipoId(Integer.valueOf(739006507));
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setIdPersonaRepresentada(Long.valueOf(-7185271677134825381l));
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setIdRol(Integer.valueOf(-38593427));
            _returnRespuestaListaApoderadoRepresentantePagare.add(_returnRespuestaListaApoderadoRepresentantePagareVal1);
            _returnRespuesta.getListaApoderadoRepresentantePagare().addAll(_returnRespuestaListaApoderadoRepresentantePagare);
            java.util.List<ConsultaGiradorServiceDTO> _returnRespuestaListaCodeudoresAvalistasPagare = new java.util.ArrayList<ConsultaGiradorServiceDTO>();
            ConsultaGiradorServiceDTO _returnRespuestaListaCodeudoresAvalistasPagareVal1 = new ConsultaGiradorServiceDTO();
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setGiradorCuenta(Integer.valueOf(744859228));
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setGiradorNumId("GiradorNumId-1275963641");
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setGiradorTipoId(Integer.valueOf(-1738648527));
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setIdPersonaRepresentada(Long.valueOf(-2176175591528164041l));
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setIdRol(Integer.valueOf(726276169));
            _returnRespuestaListaCodeudoresAvalistasPagare.add(_returnRespuestaListaCodeudoresAvalistasPagareVal1);
            _returnRespuesta.getListaCodeudoresAvalistasPagare().addAll(_returnRespuestaListaCodeudoresAvalistasPagare);
            _returnRespuesta.setMargenRedescuento(new java.math.BigDecimal("1046121682031714057.2053254180386154558"));
            _returnRespuesta.setMejoramientoViviendaInterSoci(Boolean.valueOf(false));
            java.util.List<java.lang.String> _returnRespuestaMensajeRespuesta = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnRespuestaMensajeRespuestaVal1 = "_returnRespuestaMensajeRespuestaVal883227698";
            _returnRespuestaMensajeRespuesta.add(_returnRespuestaMensajeRespuestaVal1);
            _returnRespuesta.getMensajeRespuesta().addAll(_returnRespuestaMensajeRespuesta);
            _returnRespuesta.setModalidad("Modalidad-766635446");
            _returnRespuesta.setModalidadPagoCapital("ModalidadPagoCapital658148495");
            _returnRespuesta.setModalidadPagosInteres("ModalidadPagosInteres-1574145607");
            _returnRespuesta.setNitEmisor("NitEmisor2011142903");
            _returnRespuesta.setNoVis(Boolean.valueOf(false));
            _returnRespuesta.setNumCredito("NumCredito1754157006");
            _returnRespuesta.setNumCuotas(Integer.valueOf(336771297));
            _returnRespuesta.setNumCuotasLetras("NumCuotasLetras1991742056");
            _returnRespuesta.setNumPagareEntidad("NumPagareEntidad1619141541");
            _returnRespuesta.setNumReferencia("NumReferencia441678848");
            _returnRespuesta.setNumUnidadesUVR(new java.math.BigDecimal("-1793604399082626786.1978608297262433957"));
            _returnRespuesta.setOtorganteCuenta(Integer.valueOf(1602335700));
            _returnRespuesta.setOtorganteNumId("OtorganteNumId-569281633");
            _returnRespuesta.setOtorganteTipoId(Integer.valueOf(-543324130));
            _returnRespuesta.setOtraModalidadPago("OtraModalidadPago-676620976");
            _returnRespuesta.setOtroDestino(Boolean.valueOf(true));
            _returnRespuesta.setPais("Pais1720839431");
            _returnRespuesta.setPaisCreacion("PaisCreacion-1565691765");
            _returnRespuesta.setPeriodicidadGracia("PeriodicidadGracia172406219");
            _returnRespuesta.setPeriodicidadMuerto("PeriodicidadMuerto-917049668");
            _returnRespuesta.setPeriodicidadPlazo("PeriodicidadPlazo591451619");
            _returnRespuesta.setPeriodoGracia(Boolean.valueOf(true));
            _returnRespuesta.setPeriodoGraciaDe(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.425-05:00"));
            _returnRespuesta.setPeriodoGraciaHasta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.425-05:00"));
            _returnRespuesta.setPeriodoGraciaLetras("PeriodoGraciaLetras1790934200");
            _returnRespuesta.setPeriodoGraciaNumero(new java.math.BigDecimal("-440852365017574048.8702404340229562313"));
            _returnRespuesta.setPeriodoMuerto(Boolean.valueOf(true));
            _returnRespuesta.setPeriodoMuertoDe(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.425-05:00"));
            _returnRespuesta.setPeriodoMuertoHasta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.426-05:00"));
            _returnRespuesta.setPeriodoMuertoLetras("PeriodoMuertoLetras-1144203100");
            _returnRespuesta.setPeriodoMuertoNumero(new java.math.BigDecimal("-1690220242866702218.4297730165843997573"));
            _returnRespuesta.setPlazoCreditoDe(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.426-05:00"));
            _returnRespuesta.setPlazoCreditoHasta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.426-05:00"));
            _returnRespuesta.setPlazoLetras("PlazoLetras-1289262527");
            _returnRespuesta.setPlazoNumero(new java.math.BigDecimal("9121777460656678359.1604463210124956735"));
            _returnRespuesta.setPorcentAmortizacionMensual(new java.math.BigDecimal("6954170574973001970.105043830665368685"));
            _returnRespuesta.setPorcentAmortizacionSemestral(new java.math.BigDecimal("7170261606218535071.2119523414211641370"));
            _returnRespuesta.setPorcentajeCobertura(new java.math.BigDecimal("5333505487119764498.2404027791295547385"));
            _returnRespuesta.setPorcentajeComision(new java.math.BigDecimal("-5908921972355515001.3660461600963650582"));
            _returnRespuesta.setPuntosPorcentualesRedescuento(new java.math.BigDecimal("1084814251485397875.3992276891357464645"));
            _returnRespuesta.setRegional("Regional-1232587139");
            _returnRespuesta.setSeguroVida(new java.math.BigDecimal("-8664801455079611913.9099226192580980200"));
            _returnRespuesta.setSpreed(new java.math.BigDecimal("-57172770083418536.8402644693017082601"));
            _returnRespuesta.setTasaInteres("TasaInteres-436235168");
            _returnRespuesta.setTasaInteresMora(new java.math.BigDecimal("2562084632182625589.8268189599092457861"));
            _returnRespuesta.setTasaInteresMoraLetras("TasaInteresMoraLetras-1544090500");
            _returnRespuesta.setTasaInteresRenumEA(new java.math.BigDecimal("-3938762805755049386.3906062861696937689"));
            _returnRespuesta.setTasaInteresRenumEALetras("TasaInteresRenumEALetras-1938338040");
            _returnRespuesta.setTasaNominal(new java.math.BigDecimal("-3038008606985072512.6643310566098244155"));
            _returnRespuesta.setTasaNominalLetras("TasaNominalLetras-201694399");
            _returnRespuesta.setTasaRedescuento(new java.math.BigDecimal("7461998630020773221.715731492247529894"));
            _returnRespuesta.setTextoAdicional("TextoAdicional1611280718");
            _returnRespuesta.setTipoPagare(Integer.valueOf(-8306181));
            _returnRespuesta.setValorCapitalLetras("ValorCapitalLetras847027990");
            _returnRespuesta.setValorCapitalNumero(new java.math.BigDecimal("-3202381888827157839.3715227466075025466"));
            _returnRespuesta.setValorCuotaPesos(new java.math.BigDecimal("6477553115971415637.6502666347470889217"));
            _returnRespuesta.setValorCuotaPesosLetras("ValorCuotaPesosLetras1797594509");
            _returnRespuesta.setValorCuotaUVR(new java.math.BigDecimal("5002045782307073664.1044714270494599217"));
            _returnRespuesta.setValorCuotaUVRLetras("ValorCuotaUVRLetras-472007631");
            _returnRespuesta.setValorDesembolsoUVRLetras("ValorDesembolsoUVRLetras125413677");
            _returnRespuesta.setValorInteresesLetras("ValorInteresesLetras-1897286231");
            _returnRespuesta.setValorInteresesNumero(new java.math.BigDecimal("2941835514393756211.8918685643297450033"));
            _returnRespuesta.setValorPesosActual(new java.math.BigDecimal("6287688044519853104.3553821735469946740"));
            _returnRespuesta.setValorPesosDesembolso(new java.math.BigDecimal("6480275815994313336.8266871583833673162"));
            _returnRespuesta.setValorPesosDesembolsoLetras("ValorPesosDesembolsoLetras-1257077988");
            _returnRespuesta.setValorPesosDiligenciamiento(new java.math.BigDecimal("-1636373659026496943.7944659248870571653"));
            _returnRespuesta.setVis(Boolean.valueOf(true));
            _return.setRespuesta(_returnRespuesta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#consultarPagares(SolicitudConsultarPagareDTO consultarPagares)*
     */
    public RespuestaConsultarPagaresDTO consultarPagares(SolicitudConsultarPagareDTO consultarPagares) { 
        LOG.info("Executing operation consultarPagares");
        System.out.println(consultarPagares);
        try {
            RespuestaConsultarPagaresDTO _return = new RespuestaConsultarPagaresDTO();
            _return.setCodigoError("CodigoError840469854");
            _return.setDescripcion("Descripcion1990423877");
            _return.setExitoso(Boolean.valueOf(false));
            java.util.List<InformacionPagareServiceDTO> _returnListaRespuesta = new java.util.ArrayList<InformacionPagareServiceDTO>();
            InformacionPagareServiceDTO _returnListaRespuestaVal1 = new InformacionPagareServiceDTO();
            _returnListaRespuestaVal1.setEstadoPagare("EstadoPagare548161109");
            _returnListaRespuestaVal1.setFechaFirmaPagare(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.427-05:00"));
            _returnListaRespuestaVal1.setFechaGrabacionPagare(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.428-05:00"));
            _returnListaRespuestaVal1.setIdPagareDeceval(Integer.valueOf(-429992128));
            _returnListaRespuestaVal1.setNombreOtorgante("NombreOtorgante-2132036823");
            _returnListaRespuestaVal1.setNumPagareEntidad("NumPagareEntidad-1133245200");
            _returnListaRespuestaVal1.setNumeroDocumentoOtorgante("NumeroDocumentoOtorgante-296111926");
            ArchivoAdjuntoDTO _returnListaRespuestaVal1PdfPagare = new ArchivoAdjuntoDTO();
            _returnListaRespuestaVal1PdfPagare.setContenido("Contenido1067196942");
            _returnListaRespuestaVal1PdfPagare.setNombreArchivo("NombreArchivo-75114558");
            _returnListaRespuestaVal1.setPdfPagare(_returnListaRespuestaVal1PdfPagare);
            _returnListaRespuestaVal1.setTipoDocumentoOtorgante("TipoDocumentoOtorgante596446361");
            _returnListaRespuesta.add(_returnListaRespuestaVal1);
            _return.getListaRespuesta().addAll(_returnListaRespuesta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#firmarPagares(SolicitudFirmarPagaresDTO firmarPagares)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresDTO firmarPagares(SolicitudFirmarPagaresDTO firmarPagares) { 
        LOG.info("Executing operation firmarPagares");
        System.out.println(firmarPagares);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresDTO();
            _return.setDescripcion("Descripcion-278640355");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#solicitudRadicacionFichaTecnicaNatural(RadicacionSolicitudRequestNatural solicitudRadicacionFichaTecnicaNatural)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaRadicacionErrorDTO solicitudRadicacionFichaTecnicaNatural(RadicacionSolicitudRequestNatural solicitudRadicacionFichaTecnicaNatural) { 
        LOG.info("Executing operation solicitudRadicacionFichaTecnicaNatural");
        System.out.println(solicitudRadicacionFichaTecnicaNatural);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaRadicacionErrorDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaRadicacionErrorDTO();
            java.util.List<ErrorDTO> _returnErrores = new java.util.ArrayList<ErrorDTO>();
            ErrorDTO _returnErroresVal1 = new ErrorDTO();
            _returnErroresVal1.setCodigo("Codigo-1688330263");
            _returnErroresVal1.setError("Error-1315589755");
            _returnErrores.add(_returnErroresVal1);
            _return.getErrores().addAll(_returnErrores);
            _return.setValido(false);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#consultarPagaresNopdf(SolicitudConsultarPagareDTO consultarPagaresNopdf)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaConsultarPagaresNopdfDTO consultarPagaresNopdf(SolicitudConsultarPagareDTO consultarPagaresNopdf) { 
        LOG.info("Executing operation consultarPagaresNopdf");
        System.out.println(consultarPagaresNopdf);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaConsultarPagaresNopdfDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaConsultarPagaresNopdfDTO();
            _return.setCodigoError("CodigoError-1841575860");
            _return.setDescripcion("Descripcion-694804128");
            _return.setExitoso(Boolean.valueOf(false));
            java.util.List<InformacionPagareServiceNopdfDTO> _returnListaRespuesta = new java.util.ArrayList<InformacionPagareServiceNopdfDTO>();
            InformacionPagareServiceNopdfDTO _returnListaRespuestaVal1 = new InformacionPagareServiceNopdfDTO();
            _returnListaRespuestaVal1.setEstadoPagare("EstadoPagare1448383191");
            _returnListaRespuestaVal1.setFechaFirmaPagare(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.429-05:00"));
            _returnListaRespuestaVal1.setFechaGrabacionPagare(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.429-05:00"));
            _returnListaRespuestaVal1.setIdEstadoPagare(Integer.valueOf(832164938));
            _returnListaRespuestaVal1.setIdPagareDeceval(Integer.valueOf(1985013270));
            _returnListaRespuestaVal1.setNombreOtorgante("NombreOtorgante1241741412");
            _returnListaRespuestaVal1.setNumPagareEntidad("NumPagareEntidad-874731560");
            _returnListaRespuestaVal1.setNumeroDocumentoOtorgante("NumeroDocumentoOtorgante-727837713");
            _returnListaRespuestaVal1.setTipoDocumentoOtorgante("TipoDocumentoOtorgante-1433906270");
            _returnListaRespuesta.add(_returnListaRespuestaVal1);
            _return.getListaRespuesta().addAll(_returnListaRespuesta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#generacionMasivaCertificados(SolicitudGeneracionMasivaCertificadosDTO generacionMasivaCertificados)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaGeneracionMasivaCertificadosDTO generacionMasivaCertificados(SolicitudGeneracionMasivaCertificadosDTO generacionMasivaCertificados) { 
        LOG.info("Executing operation generacionMasivaCertificados");
        System.out.println(generacionMasivaCertificados);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaGeneracionMasivaCertificadosDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaGeneracionMasivaCertificadosDTO();
            _return.setCodigoError("CodigoError362860334");
            _return.setCodigoSolicitud("CodigoSolicitud1539682528");
            _return.setDescripcion("Descripcion906169903");
            _return.setExitoso(Boolean.valueOf(true));
            _return.setMensajeRespuesta("MensajeRespuesta669383145");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#crearCertificadoFirma(SolicitudCertificadoFirmaPDTO crearCertificadoFirma)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearCertificadoFirmaDTO crearCertificadoFirma(SolicitudCertificadoFirmaPDTO crearCertificadoFirma) { 
        LOG.info("Executing operation crearCertificadoFirma");
        System.out.println(crearCertificadoFirma);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearCertificadoFirmaDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearCertificadoFirmaDTO();
            _return.setCodigoError("CodigoError1261574247");
            _return.setDescripcion("Descripcion1717913742");
            _return.setExitoso(Boolean.valueOf(true));
            InfoCertificadoFirmaDTO _returnInfoCertificadoFirmaDTO = new InfoCertificadoFirmaDTO();
            _returnInfoCertificadoFirmaDTO.setCelular("Celular1830313477");
            _returnInfoCertificadoFirmaDTO.setClave("Clave1389064496");
            _returnInfoCertificadoFirmaDTO.setCorreoElectronico("CorreoElectronico523851987");
            _returnInfoCertificadoFirmaDTO.setIdDocumentoPagare(Long.valueOf(3676417624678771979l));
            _returnInfoCertificadoFirmaDTO.setIdRolFirmante(Long.valueOf(4707047238715891195l));
            _returnInfoCertificadoFirmaDTO.setNumeroDocumento("NumeroDocumento492859797");
            _returnInfoCertificadoFirmaDTO.setNumeroReferencia("NumeroReferencia-1846507348");
            _returnInfoCertificadoFirmaDTO.setTipoDocumento(Integer.valueOf(1848345800));
            _return.setInfoCertificadoFirmaDTO(_returnInfoCertificadoFirmaDTO);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#notificacionPagaresFirmados(SolicitudPagaresFirmadosDTO notificacionPagaresFirmados)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaPagaresFirmadosDTO notificacionPagaresFirmados(SolicitudPagaresFirmadosDTO notificacionPagaresFirmados) { 
        LOG.info("Executing operation notificacionPagaresFirmados");
        System.out.println(notificacionPagaresFirmados);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaPagaresFirmadosDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaPagaresFirmadosDTO();
            _return.setCodigoError("CodigoError-281439120");
            _return.setDescripcion("Descripcion-1846628936");
            _return.setExitoso(Boolean.valueOf(true));
            java.util.List<PagaresFirmadosDTO> _returnListaRespusta = new java.util.ArrayList<PagaresFirmadosDTO>();
            PagaresFirmadosDTO _returnListaRespustaVal1 = new PagaresFirmadosDTO();
            _returnListaRespustaVal1.setIdDocumentoPagare(Long.valueOf(-4890792474574784134l));
            _returnListaRespustaVal1.setIdentificacionEmisor("IdentificacionEmisor-767797548");
            _returnListaRespustaVal1.setMensajeRespuesta("MensajeRespuesta1383941769");
            _returnListaRespustaVal1.setNumPagareEntidad("NumPagareEntidad1247481775");
            _returnListaRespusta.add(_returnListaRespustaVal1);
            _return.getListaRespusta().addAll(_returnListaRespusta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#cancelacionPagares(SolicitudCancelacionPagaresServiceDTO cancelacionPagares)*
     */
    public RespuestaCancelacionPagaresServiceDTO cancelacionPagares(SolicitudCancelacionPagaresServiceDTO cancelacionPagares) { 
        LOG.info("Executing operation cancelacionPagares");
        System.out.println(cancelacionPagares);
        try {
            RespuestaCancelacionPagaresServiceDTO _return = new RespuestaCancelacionPagaresServiceDTO();
            _return.setCodigoError("CodigoError-927321611");
            _return.setDescripcion("Descripcion-1262783956");
            _return.setExitoso(Boolean.valueOf(false));
            java.util.List<CancelacionPagaresServiceDTO> _returnListaRespusta = new java.util.ArrayList<CancelacionPagaresServiceDTO>();
            CancelacionPagaresServiceDTO _returnListaRespustaVal1 = new CancelacionPagaresServiceDTO();
            _returnListaRespustaVal1.setCodigoAdministradorAntCta("CodigoAdministradorAntCta-1971207549");
            _returnListaRespustaVal1.setCodigoEmisorAntCta("CodigoEmisorAntCta944973892");
            _returnListaRespustaVal1.setCodigoISINDocPag("CodigoISINDocPag-1412521190");
            _returnListaRespustaVal1.setCuentaBeneficiarioDocPag("CuentaBeneficiarioDocPag1313454615");
            _returnListaRespustaVal1.setExitoso(Boolean.valueOf(false));
            _returnListaRespustaVal1.setIdDocumentoPagareDocPag(Long.valueOf(-197853247332921806l));
            _returnListaRespustaVal1.setIdUsuarioSession(Long.valueOf(7277912355974275732l));
            _returnListaRespustaVal1.setMensajeRespuesta("MensajeRespuesta-1123292666");
            _returnListaRespustaVal1.setNombreUsuarioSession("NombreUsuarioSession2101758631");
            _returnListaRespustaVal1.setNumPagareEntidadDocPag("NumPagareEntidadDocPag111345506");
            _returnListaRespustaVal1.setOtrosValoresDetOpe(new java.math.BigDecimal("6324344212546603254.5302080285036186127"));
            _returnListaRespustaVal1.setValorAmortizacionCapitalDetOpe(new java.math.BigDecimal("6383660714787801951.3852480250726430067"));
            _returnListaRespustaVal1.setValorInteresesCtesDetOpe(new java.math.BigDecimal("3752668525695106643.2323659891944481341"));
            _returnListaRespustaVal1.setValorInteresesMoraDetOpe(new java.math.BigDecimal("1653194438157586533.8540372402808007092"));
            _returnListaRespustaVal1.setValorPagadoDetOpe(new java.math.BigDecimal("-1282001674293190053.2982675706593190330"));
            _returnListaRespustaVal1.setValorSeguroDetOpe(new java.math.BigDecimal("3659524132194348833.6936998249772604822"));
            _returnListaRespusta.add(_returnListaRespustaVal1);
            _return.getListaRespusta().addAll(_returnListaRespusta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#notificacionDesembolsoAnotacionEnCuenta(SolicitudDesembolsoAnotarCuentaDTO notificacionDesembolsoAnotacionEnCuenta)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDesembolsoAnotarCuentaDTO notificacionDesembolsoAnotacionEnCuenta(SolicitudDesembolsoAnotarCuentaDTO notificacionDesembolsoAnotacionEnCuenta) { 
        LOG.info("Executing operation notificacionDesembolsoAnotacionEnCuenta");
        System.out.println(notificacionDesembolsoAnotacionEnCuenta);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDesembolsoAnotarCuentaDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDesembolsoAnotarCuentaDTO();
            _return.setCodigoError("CodigoError-1951274358");
            _return.setDescripcion("Descripcion-1005076737");
            _return.setExitoso(Boolean.valueOf(true));
            java.util.List<DesembolsoAnotarCuentaDTO> _returnListaRespusta = new java.util.ArrayList<DesembolsoAnotarCuentaDTO>();
            DesembolsoAnotarCuentaDTO _returnListaRespustaVal1 = new DesembolsoAnotarCuentaDTO();
            _returnListaRespustaVal1.setIdDocumentoPagare(Long.valueOf(7618008494563515219l));
            _returnListaRespustaVal1.setIdentificacionEmisor("IdentificacionEmisor618158606");
            _returnListaRespustaVal1.setMensajeRespuesta("MensajeRespuesta-1683623596");
            _returnListaRespustaVal1.setNumPagareEntidad("NumPagareEntidad1800340037");
            _returnListaRespusta.add(_returnListaRespustaVal1);
            _return.getListaRespusta().addAll(_returnListaRespusta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#creacionGiradoresCodificados(SolicitudCrearGiradorDaneServiceDTO creacionGiradoresCodificados)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearGiradorDaneServiceDTO creacionGiradoresCodificados(SolicitudCrearGiradorDaneServiceDTO creacionGiradoresCodificados) { 
        LOG.info("Executing operation creacionGiradoresCodificados");
        System.out.println(creacionGiradoresCodificados);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearGiradorDaneServiceDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearGiradorDaneServiceDTO();
            _return.setCodigoError("CodigoError-371735153");
            _return.setDescripcion("Descripcion835415527");
            _return.setExitoso(Boolean.valueOf(false));
            CrearGiradorDaneServiceDTO _returnRespuesta = new CrearGiradorDaneServiceDTO();
            _returnRespuesta.setAgenteAutoretenedorJur(Integer.valueOf(384375198));
            _returnRespuesta.setCamaraComercioNoJur("CamaraComercioNoJur-178331281");
            _returnRespuesta.setCirculoNoJur("CirculoNoJur-541402466");
            _returnRespuesta.setCorreoElectronico("CorreoElectronico2106477237");
            _returnRespuesta.setCuentaGirador(-2567056955301174666l);
            _returnRespuesta.setDeclaranteJur(Integer.valueOf(834083566));
            _returnRespuesta.setDireccion1PersonaGrupoPGP("Direccion1PersonaGrupoPGP-1810450766");
            _returnRespuesta.setDireccion2PersonaGrupoPGP("Direccion2PersonaGrupoPGP834986740");
            _returnRespuesta.setDireccion3PersonaGrupoPGP("Direccion3PersonaGrupoPGP-1805749192");
            _returnRespuesta.setEscrituraNoJur("EscrituraNoJur1091926965");
            _returnRespuesta.setEstadoCivil("EstadoCivil1148808209");
            _returnRespuesta.setFax1PersonaGrupoPGP("Fax1PersonaGrupoPGP609252232");
            _returnRespuesta.setFax2PersonaGrupoPGP("Fax2PersonaGrupoPGP631717731");
            _returnRespuesta.setFax3PersonaGrupoPGP("Fax3PersonaGrupoPGP-1881811294");
            _returnRespuesta.setFechaCamaraJur(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.431-05:00"));
            _returnRespuesta.setFechaConstitucionJur(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.431-05:00"));
            _returnRespuesta.setFechaEscrituraJur(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.431-05:00"));
            _returnRespuesta.setFechaExpedicionNat(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.431-05:00"));
            _returnRespuesta.setFechaNacimientoNat(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.432-05:00"));
            _returnRespuesta.setFkIdCiudadCamaraJur("FkIdCiudadCamaraJur1447814744");
            _returnRespuesta.setFkIdCiudadDomicilioNat("FkIdCiudadDomicilioNat-1327017183");
            _returnRespuesta.setFkIdCiudadExpedicionNat("FkIdCiudadExpedicionNat1715387139");
            _returnRespuesta.setFkIdCiudadJur("FkIdCiudadJur77382700");
            _returnRespuesta.setFkIdClasePersona(Integer.valueOf(1474223974));
            _returnRespuesta.setFkIdDepartamentoCamaraJur("FkIdDepartamentoCamaraJur791425041");
            _returnRespuesta.setFkIdDepartamentoDomicilioNat("FkIdDepartamentoDomicilioNat336154113");
            _returnRespuesta.setFkIdDepartamentoExpedicionNat("FkIdDepartamentoExpedicionNat-2134214459");
            _returnRespuesta.setFkIdDepartamentoJur("FkIdDepartamentoJur346502802");
            _returnRespuesta.setFkIdPaisCamaraJur("FkIdPaisCamaraJur1225032503");
            _returnRespuesta.setFkIdPaisDomicilioNat("FkIdPaisDomicilioNat1829602540");
            _returnRespuesta.setFkIdPaisExpedicionNat("FkIdPaisExpedicionNat-2063220401");
            _returnRespuesta.setFkIdPaisNacionalidadNat("FkIdPaisNacionalidadNat-701782509");
            _returnRespuesta.setFkIdPaisJur("FkIdPaisJur553034644");
            _returnRespuesta.setFkIdTipoDocumento(Integer.valueOf(1871273979));
            _returnRespuesta.setIdentificacionEmisor("IdentificacionEmisor34984655");
            _returnRespuesta.setLibroNoJur("LibroNoJur-1823610207");
            java.util.List<RepresentanteLegalServiceDTO> _returnRespuestaListaRepresentantesLegales = new java.util.ArrayList<RepresentanteLegalServiceDTO>();
            RepresentanteLegalServiceDTO _returnRespuestaListaRepresentantesLegalesVal1 = new RepresentanteLegalServiceDTO();
            _returnRespuestaListaRepresentantesLegalesVal1.setCuenta(Integer.valueOf(-249757922));
            _returnRespuestaListaRepresentantesLegalesVal1.setIdTipoRepresentante(Integer.valueOf(1207958866));
            _returnRespuestaListaRepresentantesLegalesVal1.setNumIdentificacion("NumIdentificacion1784471903");
            _returnRespuestaListaRepresentantesLegalesVal1.setTipoIdentificacion(Integer.valueOf(1175208284));
            _returnRespuestaListaRepresentantesLegales.add(_returnRespuestaListaRepresentantesLegalesVal1);
            _returnRespuesta.getListaRepresentantesLegales().addAll(_returnRespuestaListaRepresentantesLegales);
            _returnRespuesta.setMensajeRespuesta("MensajeRespuesta735284436");
            _returnRespuesta.setNombresNatNat("NombresNatNat-1845419132");
            _returnRespuesta.setNotariaNoJur("NotariaNoJur-1225739671");
            _returnRespuesta.setNumeroCelular("NumeroCelular172122093");
            _returnRespuesta.setNumeroDocumento("NumeroDocumento-335426542");
            _returnRespuesta.setPensionado(Boolean.valueOf(true));
            _returnRespuesta.setPrimerApellidoNat("PrimerApellidoNat695049745");
            _returnRespuesta.setRazonSocialJur("RazonSocialJur650070762");
            _returnRespuesta.setRegitroSuperJur("RegitroSuperJur-835394266");
            _returnRespuesta.setResidenteJur(Integer.valueOf(-206950448));
            _returnRespuesta.setSalario(Double.valueOf(0.6423904760430744));
            _returnRespuesta.setSegundoApellidoNat("SegundoApellidoNat1927462690");
            _returnRespuesta.setTelefono1PersonaGrupoPGP("Telefono1PersonaGrupoPGP-1803542682");
            _returnRespuesta.setTelefono2PersonaGrupoPGP("Telefono2PersonaGrupoPGP-142280946");
            _returnRespuesta.setTelefono3PersonaGrupoPGP("Telefono3PersonaGrupoPGP1643289929");
            _returnRespuesta.setTiempoServicio("TiempoServicio1449664243");
            _return.setRespuesta(_returnRespuesta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#firmarPagareCaracteres(SolicitudFirmarPagaresCaracteresDTO firmarPagareCaracteres)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresCodigoErrorDTO firmarPagareCaracteres(SolicitudFirmarPagaresCaracteresDTO firmarPagareCaracteres) { 
        LOG.info("Executing operation firmarPagareCaracteres");
        System.out.println(firmarPagareCaracteres);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresCodigoErrorDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresCodigoErrorDTO();
            _return.setCodigoError("CodigoError-1301765736");
            _return.setDescripcion("Descripcion452388095");
            _return.setExitoso(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#creacionPagaresCodificado(SolicitudCrearPagareDaneServiceDTO creacionPagaresCodificado)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareDaneServiceDTO creacionPagaresCodificado(SolicitudCrearPagareDaneServiceDTO creacionPagaresCodificado) { 
        LOG.info("Executing operation creacionPagaresCodificado");
        System.out.println(creacionPagaresCodificado);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareDaneServiceDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareDaneServiceDTO();
            _return.setCodigoError("CodigoError434185138");
            _return.setDescripcion("Descripcion1887380903");
            _return.setExitoso(Boolean.valueOf(false));
            DocumentoPagareDaneServiceDTO _returnRespuesta = new DocumentoPagareDaneServiceDTO();
            _returnRespuesta.setAdquisicionVivienda(Boolean.valueOf(true));
            _returnRespuesta.setApoderadoCuenta(Integer.valueOf(438088762));
            _returnRespuesta.setApoderadoNumId("ApoderadoNumId2015152026");
            _returnRespuesta.setApoderadoTipoId(Integer.valueOf(768816851));
            java.util.List<ArchivoAdjuntoDTO> _returnRespuestaArchivosAdjuntos = new java.util.ArrayList<ArchivoAdjuntoDTO>();
            ArchivoAdjuntoDTO _returnRespuestaArchivosAdjuntosVal1 = new ArchivoAdjuntoDTO();
            _returnRespuestaArchivosAdjuntosVal1.setContenido("Contenido955617233");
            _returnRespuestaArchivosAdjuntosVal1.setNombreArchivo("NombreArchivo1826664954");
            _returnRespuestaArchivosAdjuntos.add(_returnRespuestaArchivosAdjuntosVal1);
            _returnRespuesta.getArchivosAdjuntos().addAll(_returnRespuestaArchivosAdjuntos);
            _returnRespuesta.setAutorizaDebitoAutomatico(Boolean.valueOf(true));
            _returnRespuesta.setAval(new java.math.BigDecimal("6421474785788079646.5313690156552544023"));
            _returnRespuesta.setBaseLiquidacionPlazo("BaseLiquidacionPlazo1441775851");
            _returnRespuesta.setBaseLiquidacionTasa("BaseLiquidacionTasa1946582107");
            _returnRespuesta.setCiCEApartirDelMes(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.433-05:00"));
            _returnRespuesta.setCiCEPagaderaCada(Integer.valueOf(269538692));
            _returnRespuesta.setCiConCuotasExtras(Boolean.valueOf(false));
            _returnRespuesta.setCiConPeriodoGracia(Boolean.valueOf(false));
            _returnRespuesta.setCiNumCuotasExtras(Integer.valueOf(-1112427872));
            _returnRespuesta.setCiValorCuotaExtra(new java.math.BigDecimal("-6288566539247427500.4522972430011672251"));
            _returnRespuesta.setCiudadCreacion("CiudadCreacion-454540366");
            _returnRespuesta.setCiudadDesembolso("CiudadDesembolso1706005570");
            _returnRespuesta.setCodOficina("CodOficina-920335505");
            _returnRespuesta.setCodigoGeoreferenciacion("CodigoGeoreferenciacion613797132");
            _returnRespuesta.setConstruccionViviendaIndividual(Boolean.valueOf(true));
            _returnRespuesta.setCreditoReembolsableEn("CreditoReembolsableEn-825861351");
            _returnRespuesta.setCuenta("Cuenta1220467156");
            _returnRespuesta.setDepartamento("Departamento1281581999");
            _returnRespuesta.setDeptoCreacion("DeptoCreacion1368187445");
            _returnRespuesta.setDestinoOperacion("DestinoOperacion-1004156980");
            _returnRespuesta.setDiaPago(Integer.valueOf(1118395420));
            _returnRespuesta.setDtfDessembolso(new java.math.BigDecimal("-7169682364731844324.4943154461722079970"));
            _returnRespuesta.setDtfEA("DtfEA382096795");
            _returnRespuesta.setEmpresaOtorgante("EmpresaOtorgante-840827497");
            _returnRespuesta.setFechaDesembolso(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.433-05:00"));
            _returnRespuesta.setFechaFirmaFisico(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.433-05:00"));
            _returnRespuesta.setFechaGrabacionPagare(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.433-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuota(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.433-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuotaCapital(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.434-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuotaInteres(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.434-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuotaMensual(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.434-05:00"));
            _returnRespuesta.setFechaPagoPrimerCuotaSemestral(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.434-05:00"));
            _returnRespuesta.setFechaVencimientoFinanciero(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.434-05:00"));
            _returnRespuesta.setGarantiaAdicional("GarantiaAdicional519256668");
            _returnRespuesta.setIdClaseDefinicionDocumento(Long.valueOf(-6973911936431160957l));
            _returnRespuesta.setIdDocumentoPagare(Long.valueOf(-9149768697985266440l));
            _returnRespuesta.setIdGestorDocumental("IdGestorDocumental-1692928354");
            _returnRespuesta.setListaAmortizaciones("ListaAmortizaciones1022950660");
            java.util.List<ConsultaGiradorServiceDTO> _returnRespuestaListaApoderadoRepresentantePagare = new java.util.ArrayList<ConsultaGiradorServiceDTO>();
            ConsultaGiradorServiceDTO _returnRespuestaListaApoderadoRepresentantePagareVal1 = new ConsultaGiradorServiceDTO();
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setGiradorCuenta(Integer.valueOf(1186385843));
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setGiradorNumId("GiradorNumId1669750837");
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setGiradorTipoId(Integer.valueOf(921507473));
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setIdPersonaRepresentada(Long.valueOf(-569814500393761499l));
            _returnRespuestaListaApoderadoRepresentantePagareVal1.setIdRol(Integer.valueOf(943978935));
            _returnRespuestaListaApoderadoRepresentantePagare.add(_returnRespuestaListaApoderadoRepresentantePagareVal1);
            _returnRespuesta.getListaApoderadoRepresentantePagare().addAll(_returnRespuestaListaApoderadoRepresentantePagare);
            java.util.List<ConsultaGiradorServiceDTO> _returnRespuestaListaCodeudoresAvalistasPagare = new java.util.ArrayList<ConsultaGiradorServiceDTO>();
            ConsultaGiradorServiceDTO _returnRespuestaListaCodeudoresAvalistasPagareVal1 = new ConsultaGiradorServiceDTO();
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setGiradorCuenta(Integer.valueOf(-1345076654));
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setGiradorNumId("GiradorNumId809916692");
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setGiradorTipoId(Integer.valueOf(-1127262665));
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setIdPersonaRepresentada(Long.valueOf(5036580044721453302l));
            _returnRespuestaListaCodeudoresAvalistasPagareVal1.setIdRol(Integer.valueOf(-2062413516));
            _returnRespuestaListaCodeudoresAvalistasPagare.add(_returnRespuestaListaCodeudoresAvalistasPagareVal1);
            _returnRespuesta.getListaCodeudoresAvalistasPagare().addAll(_returnRespuestaListaCodeudoresAvalistasPagare);
            _returnRespuesta.setMargenRedescuento(new java.math.BigDecimal("-1086788040972602293.5256370840887040026"));
            _returnRespuesta.setMejoramientoViviendaInterSoci(Boolean.valueOf(true));
            java.util.List<java.lang.String> _returnRespuestaMensajeRespuesta = new java.util.ArrayList<java.lang.String>();
            java.lang.String _returnRespuestaMensajeRespuestaVal1 = "_returnRespuestaMensajeRespuestaVal107952547";
            _returnRespuestaMensajeRespuesta.add(_returnRespuestaMensajeRespuestaVal1);
            _returnRespuesta.getMensajeRespuesta().addAll(_returnRespuestaMensajeRespuesta);
            _returnRespuesta.setModalidad("Modalidad1680680183");
            _returnRespuesta.setModalidadPagoCapital("ModalidadPagoCapital-604147712");
            _returnRespuesta.setModalidadPagosInteres("ModalidadPagosInteres-866759900");
            _returnRespuesta.setNitEmisor("NitEmisor1788714386");
            _returnRespuesta.setNoVis(Boolean.valueOf(false));
            _returnRespuesta.setNumCredito("NumCredito833017862");
            _returnRespuesta.setNumCuotas(Integer.valueOf(568361311));
            _returnRespuesta.setNumCuotasLetras("NumCuotasLetras1955771922");
            _returnRespuesta.setNumPagareEntidad("NumPagareEntidad1132291909");
            _returnRespuesta.setNumReferencia("NumReferencia571314194");
            _returnRespuesta.setNumUnidadesUVR(new java.math.BigDecimal("-7680003888845215507.5516848349792897295"));
            _returnRespuesta.setOtorganteCuenta(Integer.valueOf(-72294651));
            _returnRespuesta.setOtorganteNumId("OtorganteNumId796029056");
            _returnRespuesta.setOtorganteTipoId(Integer.valueOf(-420350460));
            _returnRespuesta.setOtraModalidadPago("OtraModalidadPago110847682");
            _returnRespuesta.setOtroDestino(Boolean.valueOf(false));
            _returnRespuesta.setPais("Pais-406968127");
            _returnRespuesta.setPaisCreacion("PaisCreacion-553598543");
            _returnRespuesta.setPeriodicidadGracia("PeriodicidadGracia343864211");
            _returnRespuesta.setPeriodicidadMuerto("PeriodicidadMuerto849231899");
            _returnRespuesta.setPeriodicidadPlazo("PeriodicidadPlazo-1851611006");
            _returnRespuesta.setPeriodoGracia(Boolean.valueOf(false));
            _returnRespuesta.setPeriodoGraciaDe(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.435-05:00"));
            _returnRespuesta.setPeriodoGraciaHasta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.435-05:00"));
            _returnRespuesta.setPeriodoGraciaLetras("PeriodoGraciaLetras-1776488372");
            _returnRespuesta.setPeriodoGraciaNumero(new java.math.BigDecimal("-758093416753435914.416097035547419189"));
            _returnRespuesta.setPeriodoMuerto(Boolean.valueOf(true));
            _returnRespuesta.setPeriodoMuertoDe(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.435-05:00"));
            _returnRespuesta.setPeriodoMuertoHasta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.435-05:00"));
            _returnRespuesta.setPeriodoMuertoLetras("PeriodoMuertoLetras1769344372");
            _returnRespuesta.setPeriodoMuertoNumero(new java.math.BigDecimal("1783724156676843600.8458981903812191611"));
            _returnRespuesta.setPlazoCreditoDe(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.436-05:00"));
            _returnRespuesta.setPlazoCreditoHasta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.436-05:00"));
            _returnRespuesta.setPlazoLetras("PlazoLetras1970626853");
            _returnRespuesta.setPlazoNumero(new java.math.BigDecimal("-3934924401171517255.7238847054730808158"));
            _returnRespuesta.setPorcentAmortizacionMensual(new java.math.BigDecimal("-1047770453874754341.2739540153976710094"));
            _returnRespuesta.setPorcentAmortizacionSemestral(new java.math.BigDecimal("-59493294204355612.1263142500090076964"));
            _returnRespuesta.setPorcentajeCobertura(new java.math.BigDecimal("-6535617798854361719.230842714469156537"));
            _returnRespuesta.setPorcentajeComision(new java.math.BigDecimal("-7376253799888576826.2071112163025419750"));
            _returnRespuesta.setPuntosPorcentualesRedescuento(new java.math.BigDecimal("-3487522402350657299.3797731724369024396"));
            _returnRespuesta.setRegional("Regional-632045619");
            _returnRespuesta.setSeguroVida(new java.math.BigDecimal("-1265302581694719609.8427229828120315993"));
            _returnRespuesta.setSpreed(new java.math.BigDecimal("1340346749042929078.2099320849580734178"));
            _returnRespuesta.setTasaInteres("TasaInteres973656846");
            _returnRespuesta.setTasaInteresMora(new java.math.BigDecimal("-6954322759224036918.462422912298050849"));
            _returnRespuesta.setTasaInteresMoraLetras("TasaInteresMoraLetras441822775");
            _returnRespuesta.setTasaInteresRenumEA(new java.math.BigDecimal("-7784348379816173898.3155742092108580664"));
            _returnRespuesta.setTasaInteresRenumEALetras("TasaInteresRenumEALetras183384216");
            _returnRespuesta.setTasaNominal(new java.math.BigDecimal("5630349134424783013.1478430917937694061"));
            _returnRespuesta.setTasaNominalLetras("TasaNominalLetras996625698");
            _returnRespuesta.setTasaRedescuento(new java.math.BigDecimal("-12697581160590846.7311856751213802138"));
            _returnRespuesta.setTextoAdicional("TextoAdicional-630872944");
            _returnRespuesta.setTipoPagare(Integer.valueOf(-1711506473));
            _returnRespuesta.setValorCapitalLetras("ValorCapitalLetras534370912");
            _returnRespuesta.setValorCapitalNumero(new java.math.BigDecimal("-6195847914316528459.5210110455614377665"));
            _returnRespuesta.setValorCuotaPesos(new java.math.BigDecimal("-8019741455079008980.8789217722116179933"));
            _returnRespuesta.setValorCuotaPesosLetras("ValorCuotaPesosLetras385384290");
            _returnRespuesta.setValorCuotaUVR(new java.math.BigDecimal("2473887711530013023.2758010998719793167"));
            _returnRespuesta.setValorCuotaUVRLetras("ValorCuotaUVRLetras-1948964581");
            _returnRespuesta.setValorDesembolsoUVRLetras("ValorDesembolsoUVRLetras-1554242788");
            _returnRespuesta.setValorInteresesLetras("ValorInteresesLetras-849333146");
            _returnRespuesta.setValorInteresesNumero(new java.math.BigDecimal("6455816182729139175.2709827542777602806"));
            _returnRespuesta.setValorPesosActual(new java.math.BigDecimal("-3134919092880747117.5443782781676436071"));
            _returnRespuesta.setValorPesosDesembolso(new java.math.BigDecimal("-5647342127337090035.1260426879786786887"));
            _returnRespuesta.setValorPesosDesembolsoLetras("ValorPesosDesembolsoLetras-1561801607");
            _returnRespuesta.setValorPesosDiligenciamiento(new java.math.BigDecimal("1018979950894327197.6284248368657184990"));
            _returnRespuesta.setVis(Boolean.valueOf(true));
            _return.setRespuesta(_returnRespuesta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#firmarPagareConCertificado(SolicitudFirmarPagaresConCertificadoDTO firmarPagareConCertificado)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresDTO firmarPagareConCertificado(SolicitudFirmarPagaresConCertificadoDTO firmarPagareConCertificado) { 
        LOG.info("Executing operation firmarPagareConCertificado");
        System.out.println(firmarPagareConCertificado);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresDTO();
            _return.setDescripcion("Descripcion1170081684");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#registrarAmortizacion(SolicitudAmortizacionSaldosServiceDTO registrarAmortizacion)*
     */
    public RespuestaAmortizacionSaldosServiceDTO registrarAmortizacion(SolicitudAmortizacionSaldosServiceDTO registrarAmortizacion) { 
        LOG.info("Executing operation registrarAmortizacion");
        System.out.println(registrarAmortizacion);
        try {
            RespuestaAmortizacionSaldosServiceDTO _return = new RespuestaAmortizacionSaldosServiceDTO();
            _return.setCodigoError("CodigoError-379511442");
            _return.setDescripcion("Descripcion-1555824203");
            _return.setExitoso(Boolean.valueOf(true));
            java.util.List<AmortizacionSaldosServiceDTO> _returnListaRespusta = new java.util.ArrayList<AmortizacionSaldosServiceDTO>();
            AmortizacionSaldosServiceDTO _returnListaRespustaVal1 = new AmortizacionSaldosServiceDTO();
            _returnListaRespustaVal1.setCodigoAdministradorAntCta("CodigoAdministradorAntCta294690374");
            _returnListaRespustaVal1.setCodigoEmisorAntCta("CodigoEmisorAntCta-852171485");
            _returnListaRespustaVal1.setCodigoISINDocPag("CodigoISINDocPag1025301668");
            _returnListaRespustaVal1.setCuentaBeneficiarioDocPag("CuentaBeneficiarioDocPag30880325");
            _returnListaRespustaVal1.setExitoso(Boolean.valueOf(true));
            _returnListaRespustaVal1.setIdDocumentoPagareDocPag(Long.valueOf(7975987197624836248l));
            _returnListaRespustaVal1.setIdUsuarioSession(Long.valueOf(-798573695057552075l));
            _returnListaRespustaVal1.setMensajeRespuesta("MensajeRespuesta-1195664289");
            _returnListaRespustaVal1.setNombreUsuarioSession("NombreUsuarioSession786770921");
            _returnListaRespustaVal1.setNumPagareEntidadDocPag("NumPagareEntidadDocPag1447838683");
            _returnListaRespustaVal1.setOtrosValoresDetOpe(new java.math.BigDecimal("7562395520270342944.1609112472365832390"));
            _returnListaRespustaVal1.setValorAmortizacionCapitalDetOpe(new java.math.BigDecimal("-8804034732262287524.369730959165290118"));
            _returnListaRespustaVal1.setValorInteresesCtesDetOpe(new java.math.BigDecimal("-7413440649687275045.7333785872185927233"));
            _returnListaRespustaVal1.setValorInteresesMoraDetOpe(new java.math.BigDecimal("338275736647449693.2523676063826538825"));
            _returnListaRespustaVal1.setValorPagadoDetOpe(new java.math.BigDecimal("-7883153001038588394.8132948872963208653"));
            _returnListaRespustaVal1.setValorSeguroDetOpe(new java.math.BigDecimal("5665739620009851736.721245890269011463"));
            _returnListaRespusta.add(_returnListaRespustaVal1);
            _return.getListaRespusta().addAll(_returnListaRespusta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#creacionPagares(SolicitudCrearPagareServiceDTO creacionPagares)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareServiceDTO creacionPagares(SolicitudCrearPagareServiceDTO creacionPagares) { 
        LOG.info("Executing operation creacionPagares");
        System.out.println(creacionPagares);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareServiceDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareServiceDTO();
            _return.setCodigoError("CodigoError-458244134");
            _return.setDescripcion("Descripcion-223898478");
            _return.setExitoso(Boolean.valueOf(true));
            java.util.List<DocumentoPagareServiceDTO> _returnListaRespusta = new java.util.ArrayList<DocumentoPagareServiceDTO>();
            DocumentoPagareServiceDTO _returnListaRespustaVal1 = new DocumentoPagareServiceDTO();
            _returnListaRespustaVal1.setAdquisicionVivienda(Boolean.valueOf(false));
            _returnListaRespustaVal1.setApoderadoCuenta(Integer.valueOf(491433036));
            _returnListaRespustaVal1.setApoderadoNumId("ApoderadoNumId-1892183944");
            _returnListaRespustaVal1.setApoderadoTipoId(Integer.valueOf(849783711));
            java.util.List<ArchivoAdjuntoDTO> _returnListaRespustaVal1ArchivosAdjuntos = new java.util.ArrayList<ArchivoAdjuntoDTO>();
            _returnListaRespustaVal1.getArchivosAdjuntos().addAll(_returnListaRespustaVal1ArchivosAdjuntos);
            _returnListaRespustaVal1.setAutorizaDebitoAutomatico(Boolean.valueOf(false));
            _returnListaRespustaVal1.setAval(new java.math.BigDecimal("-7594519392611388029.748329096928973954"));
            _returnListaRespustaVal1.setBaseLiquidacionPlazo("BaseLiquidacionPlazo847122452");
            _returnListaRespustaVal1.setBaseLiquidacionTasa("BaseLiquidacionTasa594073244");
            _returnListaRespustaVal1.setCiCEApartirDelMes(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.438-05:00"));
            _returnListaRespustaVal1.setCiCEPagaderaCada(Integer.valueOf(1611707738));
            _returnListaRespustaVal1.setCiConCuotasExtras(Boolean.valueOf(true));
            _returnListaRespustaVal1.setCiConPeriodoGracia(Boolean.valueOf(true));
            _returnListaRespustaVal1.setCiNumCuotasExtras(Integer.valueOf(846962451));
            _returnListaRespustaVal1.setCiValorCuotaExtra(new java.math.BigDecimal("-6666422207399518436.4667839466015921707"));
            _returnListaRespustaVal1.setCiudadCreacion("CiudadCreacion-1644287090");
            _returnListaRespustaVal1.setCiudadDesembolso("CiudadDesembolso1084416724");
            _returnListaRespustaVal1.setCodOficina("CodOficina405571081");
            _returnListaRespustaVal1.setConstruccionViviendaIndividual(Boolean.valueOf(false));
            _returnListaRespustaVal1.setCreditoReembolsableEn("CreditoReembolsableEn1671350354");
            _returnListaRespustaVal1.setCuenta("Cuenta1445303843");
            _returnListaRespustaVal1.setDepartamento("Departamento-1610984061");
            _returnListaRespustaVal1.setDeptoCreacion("DeptoCreacion1523833324");
            _returnListaRespustaVal1.setDestinoOperacion("DestinoOperacion300366219");
            _returnListaRespustaVal1.setDiaPago(Integer.valueOf(-848926138));
            _returnListaRespustaVal1.setDtfDessembolso(new java.math.BigDecimal("-2016856371170893452.6833781054880662569"));
            _returnListaRespustaVal1.setDtfEA("DtfEA-1976343512");
            _returnListaRespustaVal1.setEmpresaOtorgante("EmpresaOtorgante530590937");
            _returnListaRespustaVal1.setFechaDesembolso(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.438-05:00"));
            _returnListaRespustaVal1.setFechaGrabacionPagare(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.438-05:00"));
            _returnListaRespustaVal1.setFechaPagoPrimerCuota(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.439-05:00"));
            _returnListaRespustaVal1.setFechaPagoPrimerCuotaCapital(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.439-05:00"));
            _returnListaRespustaVal1.setFechaPagoPrimerCuotaInteres(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.439-05:00"));
            _returnListaRespustaVal1.setFechaPagoPrimerCuotaMensual(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.439-05:00"));
            _returnListaRespustaVal1.setFechaPagoPrimerCuotaSemestral(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.439-05:00"));
            _returnListaRespustaVal1.setFechaVencimientoFinanciero(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.439-05:00"));
            _returnListaRespustaVal1.setGarantiaAdicional("GarantiaAdicional2012223178");
            _returnListaRespustaVal1.setIdClaseDefinicionDocumento(Long.valueOf(1667534382116290834l));
            _returnListaRespustaVal1.setIdDocumentoPagare(Long.valueOf(262302634974457620l));
            _returnListaRespustaVal1.setListaAmortizaciones("ListaAmortizaciones-1791387565");
            java.util.List<ConsultaGiradorServiceDTO> _returnListaRespustaVal1ListaApoderadoRepresentantePagare = new java.util.ArrayList<ConsultaGiradorServiceDTO>();
            _returnListaRespustaVal1.getListaApoderadoRepresentantePagare().addAll(_returnListaRespustaVal1ListaApoderadoRepresentantePagare);
            java.util.List<ConsultaGiradorServiceDTO> _returnListaRespustaVal1ListaCodeudoresAvalistasPagare = new java.util.ArrayList<ConsultaGiradorServiceDTO>();
            _returnListaRespustaVal1.getListaCodeudoresAvalistasPagare().addAll(_returnListaRespustaVal1ListaCodeudoresAvalistasPagare);
            _returnListaRespustaVal1.setMargenRedescuento(new java.math.BigDecimal("3376236756387688781.1069350498005365520"));
            _returnListaRespustaVal1.setMejoramientoViviendaInterSoci(Boolean.valueOf(false));
            _returnListaRespustaVal1.setMensajeRespuesta("MensajeRespuesta-1321180405");
            _returnListaRespustaVal1.setModalidad("Modalidad802719274");
            _returnListaRespustaVal1.setModalidadPagoCapital("ModalidadPagoCapital466183388");
            _returnListaRespustaVal1.setModalidadPagosInteres("ModalidadPagosInteres109304230");
            _returnListaRespustaVal1.setNitEmisor("NitEmisor-1391124183");
            _returnListaRespustaVal1.setNoVis(Boolean.valueOf(false));
            _returnListaRespustaVal1.setNumCredito("NumCredito552687674");
            _returnListaRespustaVal1.setNumCuotas(Integer.valueOf(-315062882));
            _returnListaRespustaVal1.setNumCuotasLetras("NumCuotasLetras1982124911");
            _returnListaRespustaVal1.setNumPagareEntidad("NumPagareEntidad2090573806");
            _returnListaRespustaVal1.setNumReferencia("NumReferencia1122610576");
            _returnListaRespustaVal1.setNumUnidadesUVR(new java.math.BigDecimal("-900186569324637179.4312413530855077526"));
            _returnListaRespustaVal1.setOtorganteCuenta(Integer.valueOf(1054206116));
            _returnListaRespustaVal1.setOtorganteNumId("OtorganteNumId2011966058");
            _returnListaRespustaVal1.setOtorganteTipoId(Integer.valueOf(-2084588733));
            _returnListaRespustaVal1.setOtraModalidadPago("OtraModalidadPago-645577135");
            _returnListaRespustaVal1.setOtroDestino(Boolean.valueOf(false));
            _returnListaRespustaVal1.setPais("Pais839565738");
            _returnListaRespustaVal1.setPaisCreacion("PaisCreacion-357007760");
            _returnListaRespustaVal1.setPeriodicidadGracia("PeriodicidadGracia858420321");
            _returnListaRespustaVal1.setPeriodicidadMuerto("PeriodicidadMuerto-1719465065");
            _returnListaRespustaVal1.setPeriodicidadPlazo("PeriodicidadPlazo1844268496");
            _returnListaRespustaVal1.setPeriodoGracia(Boolean.valueOf(true));
            _returnListaRespustaVal1.setPeriodoGraciaDe(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.440-05:00"));
            _returnListaRespustaVal1.setPeriodoGraciaHasta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.440-05:00"));
            _returnListaRespustaVal1.setPeriodoGraciaLetras("PeriodoGraciaLetras662094230");
            _returnListaRespustaVal1.setPeriodoGraciaNumero(new java.math.BigDecimal("-4784008163991710568.379371329951354424"));
            _returnListaRespustaVal1.setPeriodoMuerto(Boolean.valueOf(false));
            _returnListaRespustaVal1.setPeriodoMuertoDe(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.440-05:00"));
            _returnListaRespustaVal1.setPeriodoMuertoHasta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.440-05:00"));
            _returnListaRespustaVal1.setPeriodoMuertoLetras("PeriodoMuertoLetras976620905");
            _returnListaRespustaVal1.setPeriodoMuertoNumero(new java.math.BigDecimal("-6832197410190381337.6511343597469764737"));
            _returnListaRespustaVal1.setPlazoCreditoDe(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.441-05:00"));
            _returnListaRespustaVal1.setPlazoCreditoHasta(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.441-05:00"));
            _returnListaRespustaVal1.setPlazoLetras("PlazoLetras1017675804");
            _returnListaRespustaVal1.setPlazoNumero(new java.math.BigDecimal("5412844408297576230.4033797484350015602"));
            _returnListaRespustaVal1.setPorcentAmortizacionMensual(new java.math.BigDecimal("5681336429117897132.5143375533884964314"));
            _returnListaRespustaVal1.setPorcentAmortizacionSemestral(new java.math.BigDecimal("-599394017081697892.8411104407300874681"));
            _returnListaRespustaVal1.setPorcentajeCobertura(new java.math.BigDecimal("7078592331256672591.612440152169256857"));
            _returnListaRespustaVal1.setPorcentajeComision(new java.math.BigDecimal("-7527296779825985357.5986105199358905346"));
            _returnListaRespustaVal1.setPuntosPorcentualesRedescuento(new java.math.BigDecimal("1452537539355267662.6065119053035694229"));
            _returnListaRespustaVal1.setRegional("Regional-2106619586");
            _returnListaRespustaVal1.setSeguroVida(new java.math.BigDecimal("430397792349743574.4673797788642350373"));
            _returnListaRespustaVal1.setSpreed(new java.math.BigDecimal("-8987668544254768635.4458654712028502914"));
            _returnListaRespustaVal1.setTasaInteres("TasaInteres-1876448024");
            _returnListaRespustaVal1.setTasaInteresMora(new java.math.BigDecimal("-6483707315710594713.2442699779705020941"));
            _returnListaRespustaVal1.setTasaInteresMoraLetras("TasaInteresMoraLetras-1479824535");
            _returnListaRespustaVal1.setTasaInteresRenumEA(new java.math.BigDecimal("3537933040961891549.5309684590810961106"));
            _returnListaRespustaVal1.setTasaInteresRenumEALetras("TasaInteresRenumEALetras-1453436611");
            _returnListaRespustaVal1.setTasaNominal(new java.math.BigDecimal("-5323125255764245974.8981612778294754126"));
            _returnListaRespustaVal1.setTasaNominalLetras("TasaNominalLetras829162327");
            _returnListaRespustaVal1.setTasaRedescuento(new java.math.BigDecimal("-8677648488808625360.610094545567685617"));
            _returnListaRespustaVal1.setTextoAdicional("TextoAdicional-786974880");
            _returnListaRespustaVal1.setTipoPagare(Integer.valueOf(-1073369700));
            _returnListaRespustaVal1.setValorCapitalLetras("ValorCapitalLetras1772550094");
            _returnListaRespustaVal1.setValorCapitalNumero(new java.math.BigDecimal("8004181571227081496.7571175465067189686"));
            _returnListaRespustaVal1.setValorCuotaPesos(new java.math.BigDecimal("-2540096716514176215.3541469933547659576"));
            _returnListaRespustaVal1.setValorCuotaPesosLetras("ValorCuotaPesosLetras-1898337235");
            _returnListaRespustaVal1.setValorCuotaUVR(new java.math.BigDecimal("3317742438327898984.647865597898102231"));
            _returnListaRespustaVal1.setValorCuotaUVRLetras("ValorCuotaUVRLetras1833103617");
            _returnListaRespustaVal1.setValorDesembolsoUVRLetras("ValorDesembolsoUVRLetras1028207363");
            _returnListaRespustaVal1.setValorInteresesLetras("ValorInteresesLetras-401237554");
            _returnListaRespustaVal1.setValorInteresesNumero(new java.math.BigDecimal("2433300201142613270.6561078680716134574"));
            _returnListaRespustaVal1.setValorPesosActual(new java.math.BigDecimal("-7415182389462469910.4208473438761477783"));
            _returnListaRespustaVal1.setValorPesosDesembolso(new java.math.BigDecimal("8446475179101892556.4254082046041713733"));
            _returnListaRespustaVal1.setValorPesosDesembolsoLetras("ValorPesosDesembolsoLetras1845485334");
            _returnListaRespustaVal1.setValorPesosDiligenciamiento(new java.math.BigDecimal("-1788406341107056220.6344718090089519526"));
            _returnListaRespustaVal1.setVis(Boolean.valueOf(true));
            _returnListaRespusta.add(_returnListaRespustaVal1);
            _return.getListaRespusta().addAll(_returnListaRespusta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#firmarPagaresAsincrono(SolicitudFirmarPagaresDTO firmarPagaresAsincrono)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresAsincronoDTO firmarPagaresAsincrono(SolicitudFirmarPagaresDTO firmarPagaresAsincrono) { 
        LOG.info("Executing operation firmarPagaresAsincrono");
        System.out.println(firmarPagaresAsincrono);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresAsincronoDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresAsincronoDTO();
            _return.setCodigoError("CodigoError923478908");
            _return.setDescripcion("Descripcion-1113171625");
            _return.setExitoso(Boolean.valueOf(true));
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see SDLService#creacionGiradores(SolicitudCrearGiradorServiceDTO creacionGiradores)*
     */
    public com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearGiradorServiceDTO creacionGiradores(SolicitudCrearGiradorServiceDTO creacionGiradores) { 
        LOG.info("Executing operation creacionGiradores");
        System.out.println(creacionGiradores);
        try {
            com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearGiradorServiceDTO _return = new com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearGiradorServiceDTO();
            _return.setCodigoError("CodigoError1917937286");
            _return.setDescripcion("Descripcion455587888");
            _return.setExitoso(Boolean.valueOf(true));
            java.util.List<CrearGiradorServiceDTO> _returnListaRespusta = new java.util.ArrayList<CrearGiradorServiceDTO>();
            CrearGiradorServiceDTO _returnListaRespustaVal1 = new CrearGiradorServiceDTO();
            _returnListaRespustaVal1.setAgenteAutoretenedorJur(Integer.valueOf(-1117555004));
            _returnListaRespustaVal1.setCamaraComercioNoJur("CamaraComercioNoJur533430841");
            _returnListaRespustaVal1.setCirculoNoJur("CirculoNoJur-901108563");
            _returnListaRespustaVal1.setCorreoElectronico("CorreoElectronico-1890322750");
            _returnListaRespustaVal1.setCuentaGirador(-7677902576347906736l);
            _returnListaRespustaVal1.setDeclaranteJur(Integer.valueOf(-161649980));
            _returnListaRespustaVal1.setDireccion1PersonaGrupoPGP("Direccion1PersonaGrupoPGP1706600763");
            _returnListaRespustaVal1.setDireccion2PersonaGrupoPGP("Direccion2PersonaGrupoPGP1107341326");
            _returnListaRespustaVal1.setDireccion3PersonaGrupoPGP("Direccion3PersonaGrupoPGP807227946");
            _returnListaRespustaVal1.setEscrituraNoJur("EscrituraNoJur-1454255075");
            _returnListaRespustaVal1.setEstadoCivil("EstadoCivil-98573023");
            _returnListaRespustaVal1.setFax1PersonaGrupoPGP("Fax1PersonaGrupoPGP1895944061");
            _returnListaRespustaVal1.setFax2PersonaGrupoPGP("Fax2PersonaGrupoPGP-1151161513");
            _returnListaRespustaVal1.setFax3PersonaGrupoPGP("Fax3PersonaGrupoPGP-1750783892");
            _returnListaRespustaVal1.setFechaCamaraJur(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.442-05:00"));
            _returnListaRespustaVal1.setFechaConstitucionJur(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.442-05:00"));
            _returnListaRespustaVal1.setFechaEscrituraJur(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.442-05:00"));
            _returnListaRespustaVal1.setFechaExpedicionNat(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.443-05:00"));
            _returnListaRespustaVal1.setFechaNacimientoNat(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2017-09-19T12:15:59.443-05:00"));
            _returnListaRespustaVal1.setFkIdCiudadCamaraJur(Integer.valueOf(1151023739));
            _returnListaRespustaVal1.setFkIdCiudadDomicilioNat(Integer.valueOf(2001345311));
            _returnListaRespustaVal1.setFkIdCiudadExpedicionNat(Integer.valueOf(1822150234));
            _returnListaRespustaVal1.setFkIdCiudadJur(Integer.valueOf(1674416867));
            _returnListaRespustaVal1.setFkIdClasePersona(Integer.valueOf(1936019964));
            _returnListaRespustaVal1.setFkIdDepartamentoCamaraJur(Integer.valueOf(-1048788178));
            _returnListaRespustaVal1.setFkIdDepartamentoDomicilioNat(Integer.valueOf(1778675376));
            _returnListaRespustaVal1.setFkIdDepartamentoExpedicionNat(Integer.valueOf(239311591));
            _returnListaRespustaVal1.setFkIdDepartamentoJur(Integer.valueOf(-1957748311));
            _returnListaRespustaVal1.setFkIdPaisCamaraJur(Integer.valueOf(-16332440));
            _returnListaRespustaVal1.setFkIdPaisDomicilioNat(Integer.valueOf(-1873072879));
            _returnListaRespustaVal1.setFkIdPaisExpedicionNat(Integer.valueOf(560851973));
            _returnListaRespustaVal1.setFkIdPaisNacionalidadNat(Integer.valueOf(-575060034));
            _returnListaRespustaVal1.setFkIdPaisJur(Integer.valueOf(-417100763));
            _returnListaRespustaVal1.setFkIdTipoDocumento(Integer.valueOf(-113981707));
            _returnListaRespustaVal1.setIdentificacionEmisor("IdentificacionEmisor-445830873");
            _returnListaRespustaVal1.setLibroNoJur("LibroNoJur34451410");
            java.util.List<RepresentanteLegalServiceDTO> _returnListaRespustaVal1ListaRepresentantesLegales = new java.util.ArrayList<RepresentanteLegalServiceDTO>();
            _returnListaRespustaVal1.getListaRepresentantesLegales().addAll(_returnListaRespustaVal1ListaRepresentantesLegales);
            _returnListaRespustaVal1.setMensajeRespuesta("MensajeRespuesta825650859");
            _returnListaRespustaVal1.setNombresNatNat("NombresNatNat1272199769");
            _returnListaRespustaVal1.setNotariaNoJur("NotariaNoJur-319471870");
            _returnListaRespustaVal1.setNumeroCelular("NumeroCelular-1454643655");
            _returnListaRespustaVal1.setNumeroDocumento("NumeroDocumento1386623681");
            _returnListaRespustaVal1.setPensionado(Boolean.valueOf(true));
            _returnListaRespustaVal1.setPrimerApellidoNat("PrimerApellidoNat759491026");
            _returnListaRespustaVal1.setRazonSocialJur("RazonSocialJur-1904427607");
            _returnListaRespustaVal1.setRegitroSuperJur("RegitroSuperJur-1306798207");
            _returnListaRespustaVal1.setResidenteJur(Integer.valueOf(-875574142));
            _returnListaRespustaVal1.setSalario(Double.valueOf(0.09038366453209346));
            _returnListaRespustaVal1.setSegundoApellidoNat("SegundoApellidoNat1003491698");
            _returnListaRespustaVal1.setTelefono1PersonaGrupoPGP("Telefono1PersonaGrupoPGP-1272064199");
            _returnListaRespustaVal1.setTelefono2PersonaGrupoPGP("Telefono2PersonaGrupoPGP-1999149628");
            _returnListaRespustaVal1.setTelefono3PersonaGrupoPGP("Telefono3PersonaGrupoPGP-1070433277");
            _returnListaRespustaVal1.setTiempoServicio("TiempoServicio-374362155");
            _returnListaRespusta.add(_returnListaRespustaVal1);
            _return.getListaRespusta().addAll(_returnListaRespusta);
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
