package com.ebssas.wsrestapicoopedac.deceval.sdl.services;

import com.ebssas.wsrestapicoopedac.deceval.sdl.services.ObjectFactory;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RadicacionSolicitudRequestNatural;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaAmortizacionSaldosServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCancelacionPagaresServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaConsultarPagaresDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaConsultarPagaresNopdfDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearCertificadoFirmaDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearGiradorDaneServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaCrearGiradorServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDesembolsoAnotarCuentaDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareDaneServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaDocumentoPagareServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresAsincronoDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresCodigoErrorDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaFirmarPagaresDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaGeneracionMasivaCertificadosDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaPagaresFirmadosDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.RespuestaRadicacionErrorDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudAmortizacionSaldosServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudCancelacionPagaresServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudCertificadoFirmaPDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudConsultarPagareDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudCrearGiradorDaneServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudCrearGiradorServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudCrearPagareDaneServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudCrearPagareServiceDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudDesembolsoAnotarCuentaDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudFirmarPagaresCaracteresDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudFirmarPagaresConCertificadoDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudFirmarPagaresDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudGeneracionMasivaCertificadosDTO;
import com.ebssas.wsrestapicoopedac.deceval.sdl.services.SolicitudPagaresFirmadosDTO;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2017-09-19T12:15:59.443-05:00
 * Generated source version: 3.0.10
 * 
 */
@WebService(targetNamespace = "http://deceval.com/sdl/services/", name = "SDLService")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface SDLService {

    @WebMethod(action = "CreacionPagaresFisicosCodificado")
    @Action(input = "CreacionPagaresFisicosCodificado", output = "http://deceval.com/sdl/services/SDLService/creacionPagaresFisicosCodificadoResponse")
    @WebResult(name = "RespuestaDocumentoPagareDaneServiceDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaDocumentoPagareDaneServiceDTO")
    public RespuestaDocumentoPagareDaneServiceDTO creacionPagaresFisicosCodificado(
        @WebParam(partName = "creacionPagaresFisicosCodificado", name = "creacionPagaresFisicosCodificado", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudCrearPagareDaneServiceDTO creacionPagaresFisicosCodificado
    );

    @WebMethod(action = "ConsultarPagares")
    @Action(input = "ConsultarPagares", output = "http://deceval.com/sdl/services/SDLService/consultarPagaresResponse")
    @WebResult(name = "RespuestaConsultarPagaresDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaConsultarPagaresDTO")
    public RespuestaConsultarPagaresDTO consultarPagares(
        @WebParam(partName = "consultarPagares", name = "consultarPagares", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudConsultarPagareDTO consultarPagares
    );

    @WebMethod(action = "FirmarPagares")
    @Action(input = "FirmarPagares", output = "http://deceval.com/sdl/services/SDLService/firmarPagaresResponse")
    @WebResult(name = "RespuestaFirmarPagaresDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaFirmarPagaresDTO")
    public RespuestaFirmarPagaresDTO firmarPagares(
        @WebParam(partName = "firmarPagares", name = "firmarPagares", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudFirmarPagaresDTO firmarPagares
    );

    @WebMethod(action = "SolicitudRadicacionFichaTecnicaNatural")
    @Action(input = "SolicitudRadicacionFichaTecnicaNatural", output = "http://deceval.com/sdl/services/SDLService/solicitudRadicacionFichaTecnicaNaturalResponse")
    @WebResult(name = "RespuestaRadicacionErrorDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaRadicacionErrorDTO")
    public RespuestaRadicacionErrorDTO solicitudRadicacionFichaTecnicaNatural(
        @WebParam(partName = "solicitudRadicacionFichaTecnicaNatural", name = "solicitudRadicacionFichaTecnicaNatural", targetNamespace = "http://deceval.com/sdl/services/")
        RadicacionSolicitudRequestNatural solicitudRadicacionFichaTecnicaNatural
    );

    @WebMethod(action = "ConsultarPagaresNopdf")
    @Action(input = "ConsultarPagaresNopdf", output = "http://deceval.com/sdl/services/SDLService/consultarPagaresNopdfResponse")
    @WebResult(name = "RespuestaConsultarPagaresNopdfDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaConsultarPagaresNopdfDTO")
    public RespuestaConsultarPagaresNopdfDTO consultarPagaresNopdf(
        @WebParam(partName = "consultarPagaresNopdf", name = "consultarPagaresNopdf", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudConsultarPagareDTO consultarPagaresNopdf
    );

    @WebMethod(action = "GeneracionMasivaCertificados")
    @Action(input = "GeneracionMasivaCertificados", output = "http://deceval.com/sdl/services/SDLService/generacionMasivaCertificadosResponse")
    @WebResult(name = "RespuestaGeneracionMasivaCertificadosDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaGeneracionMasivaCertificadosDTO")
    public RespuestaGeneracionMasivaCertificadosDTO generacionMasivaCertificados(
        @WebParam(partName = "generacionMasivaCertificados", name = "generacionMasivaCertificados", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudGeneracionMasivaCertificadosDTO generacionMasivaCertificados
    );

    @WebMethod(action = "CrearCertificadoFirma")
    @Action(input = "CrearCertificadoFirma", output = "http://deceval.com/sdl/services/SDLService/crearCertificadoFirmaResponse")
    @WebResult(name = "RespuestaCrearCertificadoFirmaDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaCrearCertificadoFirmaDTO")
    public RespuestaCrearCertificadoFirmaDTO crearCertificadoFirma(
        @WebParam(partName = "crearCertificadoFirma", name = "crearCertificadoFirma", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudCertificadoFirmaPDTO crearCertificadoFirma
    );

    @WebMethod(action = "NotificacionPagaresFirmados")
    @Action(input = "NotificacionPagaresFirmados", output = "http://deceval.com/sdl/services/SDLService/notificacionPagaresFirmadosResponse")
    @WebResult(name = "RespuestaPagaresFirmadosDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaPagaresFirmadosDTO")
    public RespuestaPagaresFirmadosDTO notificacionPagaresFirmados(
        @WebParam(partName = "notificacionPagaresFirmados", name = "notificacionPagaresFirmados", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudPagaresFirmadosDTO notificacionPagaresFirmados
    );

    @WebMethod(action = "CancelacionPagares")
    @Action(input = "CancelacionPagares", output = "http://deceval.com/sdl/services/SDLService/cancelacionPagaresResponse")
    @WebResult(name = "RespuestaCancelacionPagaresServiceDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaCancelacionPagaresServiceDTO")
    public RespuestaCancelacionPagaresServiceDTO cancelacionPagares(
        @WebParam(partName = "cancelacionPagares", name = "cancelacionPagares", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudCancelacionPagaresServiceDTO cancelacionPagares
    );

    @WebMethod(action = "NotificacionDesembolsoAnotacionEnCuenta")
    @Action(input = "NotificacionDesembolsoAnotacionEnCuenta", output = "http://deceval.com/sdl/services/SDLService/notificacionDesembolsoAnotacionEnCuentaResponse")
    @WebResult(name = "RespuestaDesembolsoAnotarCuentaDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaDesembolsoAnotarCuentaDTO")
    public RespuestaDesembolsoAnotarCuentaDTO notificacionDesembolsoAnotacionEnCuenta(
        @WebParam(partName = "notificacionDesembolsoAnotacionEnCuenta", name = "notificacionDesembolsoAnotacionEnCuenta", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudDesembolsoAnotarCuentaDTO notificacionDesembolsoAnotacionEnCuenta
    );

    @WebMethod(operationName = "CreacionGiradoresCodificados", action = "CreacionGiradoresCodificados")
    @Action(input = "CreacionGiradoresCodificados", output = "http://deceval.com/sdl/services/SDLService/CreacionGiradoresCodificadosResponse")
    @WebResult(name = "RespuestaCrearGiradorDaneServiceDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaCrearGiradorDaneServiceDTO")
    public RespuestaCrearGiradorDaneServiceDTO creacionGiradoresCodificados(
        @WebParam(partName = "CreacionGiradoresCodificados", name = "CreacionGiradoresCodificados", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudCrearGiradorDaneServiceDTO creacionGiradoresCodificados
    );

    @WebMethod(action = "FirmarPagareCaracteres")
    @Action(input = "FirmarPagareCaracteres", output = "http://deceval.com/sdl/services/SDLService/firmarPagareCaracteresResponse")
    @WebResult(name = "RespuestaFirmarPagaresCodigoErrorDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaFirmarPagaresCodigoErrorDTO")
    public RespuestaFirmarPagaresCodigoErrorDTO firmarPagareCaracteres(
        @WebParam(partName = "firmarPagareCaracteres", name = "firmarPagareCaracteres", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudFirmarPagaresCaracteresDTO firmarPagareCaracteres
    );

    @WebMethod(operationName = "CreacionPagaresCodificado", action = "CreacionPagaresCodificado")
    @Action(input = "CreacionPagaresCodificado", output = "http://deceval.com/sdl/services/SDLService/CreacionPagaresCodificadoResponse")
    @WebResult(name = "RespuestaDocumentoPagareDaneServiceDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaDocumentoPagareDaneServiceDTO")
    public RespuestaDocumentoPagareDaneServiceDTO creacionPagaresCodificado(
        @WebParam(partName = "CreacionPagaresCodificado", name = "CreacionPagaresCodificado", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudCrearPagareDaneServiceDTO creacionPagaresCodificado
    );

    @WebMethod(action = "FirmarPagareConCertificado")
    @Action(input = "FirmarPagareConCertificado", output = "http://deceval.com/sdl/services/SDLService/firmarPagareConCertificadoResponse")
    @WebResult(name = "RespuestaFirmarPagaresDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaFirmarPagaresDTO")
    public RespuestaFirmarPagaresDTO firmarPagareConCertificado(
        @WebParam(partName = "firmarPagareConCertificado", name = "firmarPagareConCertificado", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudFirmarPagaresConCertificadoDTO firmarPagareConCertificado
    );

    @WebMethod(action = "RegistrarAmortizacion")
    @Action(input = "RegistrarAmortizacion", output = "http://deceval.com/sdl/services/SDLService/registrarAmortizacionResponse")
    @WebResult(name = "RespuestaAmortizacionSaldosServiceDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaAmortizacionSaldosServiceDTO")
    public RespuestaAmortizacionSaldosServiceDTO registrarAmortizacion(
        @WebParam(partName = "registrarAmortizacion", name = "registrarAmortizacion", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudAmortizacionSaldosServiceDTO registrarAmortizacion
    );

    @WebMethod(action = "CreacionPagares")
    @Action(input = "CreacionPagares", output = "http://deceval.com/sdl/services/SDLService/creacionPagaresResponse")
    @WebResult(name = "RespuestaDocumentoPagareServiceDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaDocumentoPagareServiceDTO")
    public RespuestaDocumentoPagareServiceDTO creacionPagares(
        @WebParam(partName = "creacionPagares", name = "creacionPagares", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudCrearPagareServiceDTO creacionPagares
    );

    @WebMethod(action = "FirmarPagaresAsincrono")
    @Action(input = "FirmarPagaresAsincrono", output = "http://deceval.com/sdl/services/SDLService/firmarPagaresAsincronoResponse")
    @WebResult(name = "RespuestaFirmarPagaresAsincronoDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaFirmarPagaresAsincronoDTO")
    public RespuestaFirmarPagaresAsincronoDTO firmarPagaresAsincrono(
        @WebParam(partName = "firmarPagaresAsincrono", name = "firmarPagaresAsincrono", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudFirmarPagaresDTO firmarPagaresAsincrono
    );

    @WebMethod(operationName = "CreacionGiradores", action = "CreacionGiradores")
    @Action(input = "CreacionGiradores", output = "http://deceval.com/sdl/services/SDLService/CreacionGiradoresResponse")
    @WebResult(name = "RespuestaCrearGiradorServiceDTO", targetNamespace = "http://deceval.com/sdl/services/", partName = "RespuestaCrearGiradorServiceDTO")
    public RespuestaCrearGiradorServiceDTO creacionGiradores(
        @WebParam(partName = "CreacionGiradores", name = "CreacionGiradores", targetNamespace = "http://deceval.com/sdl/services/")
        SolicitudCrearGiradorServiceDTO creacionGiradores
    );
}
