package com.ebssas.wsrestapicoopedac.deceval.sdl.services;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2017-09-19T12:15:59.448-05:00
 * Generated source version: 3.0.10
 * 
 */
@WebServiceClient(name = "SDLService", 
                  wsdlLocation = "file:/D:/TRABAJO/EBS/COOPEDAC/InformacionDECEVAL/SDLService.wsdl",
                  targetNamespace = "http://deceval.com/sdl/services/") 
public class SDLService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://deceval.com/sdl/services/", "SDLService");
    public final static QName SDLServicePort = new QName("http://deceval.com/sdl/services/", "SDLServicePort");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/TRABAJO/EBS/COOPEDAC/InformacionDECEVAL/SDLService.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(SDLService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/WORKSPACES/DECEVAL/WSCLIENTES/ClientSWSPagares/WebContent/WEB-INF/wsdl/SDLService.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public SDLService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SDLService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SDLService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SDLService_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SDLService_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public SDLService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    

    /**
     *
     * @return
     *     returns SDLService
     */
    @WebEndpoint(name = "SDLServicePort")
    public SDLService getSDLServicePort() {
        return super.getPort(SDLServicePort, SDLService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SDLService
     */
    @WebEndpoint(name = "SDLServicePort")
    public SDLService getSDLServicePort(WebServiceFeature... features) {
        return super.getPort(SDLServicePort, SDLService.class, features);
    }

}
