
package com.deceval.mrc.solicitud;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2017-09-19T12:17:56.597-05:00
 * Generated source version: 3.0.10
 * 
 */
public final class WsGenerarTokenPortType_WsGenerarTokenPortTypePort_Client {

    private static final QName SERVICE_NAME = new QName("http://com/deceval/mrc/solicitud", "WsGenerarTokenService");

    private WsGenerarTokenPortType_WsGenerarTokenPortTypePort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = WsGenerarTokenService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        WsGenerarTokenService ss = new WsGenerarTokenService(wsdlURL, SERVICE_NAME);
        WsGenerarTokenPortType port = ss.getWsGenerarTokenPortTypePort();  
        
        {
        System.out.println("Invoking generarToken...");
        com.deceval.mrc.solicitud.to.InformacionPagareTO _generarToken_informacionPagareTO = new com.deceval.mrc.solicitud.to.InformacionPagareTO();
        _generarToken_informacionPagareTO.setEntidadBancariaId("EntidadBancariaId-493780554");
        _generarToken_informacionPagareTO.setEstado("Estado1053468003");
        _generarToken_informacionPagareTO.setTipoDocumentoEntidad("TipoDocumentoEntidad-86509795");
        _generarToken_informacionPagareTO.setNumeroIdentificacionEntidad("NumeroIdentificacionEntidad577847888");
        _generarToken_informacionPagareTO.setTipoDocumentoFirmante("TipoDocumentoFirmante1903156256");
        _generarToken_informacionPagareTO.setNumeroDocumentoFirmante("NumeroDocumentoFirmante1108957293");
        _generarToken_informacionPagareTO.setNombreFirmante("NombreFirmante370903126");
        _generarToken_informacionPagareTO.setApellidoFirmante("ApellidoFirmante1566661813");
        _generarToken_informacionPagareTO.setIpOrigen("IpOrigen-1054241572");
        com.deceval.mrc.solicitud.to.InformacionFirmaPagareTO _generarToken__return = port.generarToken(_generarToken_informacionPagareTO);
        System.out.println("generarToken.result=" + _generarToken__return);


        }

        System.exit(0);
    }

}
