package com.deceval.mrc.solicitud;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2017-09-19T12:17:56.642-05:00
 * Generated source version: 3.0.10
 * 
 */
@WebService(targetNamespace = "http://com/deceval/mrc/solicitud", name = "WsGenerarTokenPortType")
@XmlSeeAlso({ObjectFactory.class, com.deceval.mrc.solicitud.to.ObjectFactory.class})
public interface WsGenerarTokenPortType {

    @WebMethod
    @Action(input = "http://com/deceval/mrc/solicitud/WsGenerarTokenPortType/generarTokenRequest", output = "http://com/deceval/mrc/solicitud/WsGenerarTokenPortType/generarTokenResponse")
    @RequestWrapper(localName = "generarToken", targetNamespace = "http://com/deceval/mrc/solicitud", className = "com.deceval.mrc.solicitud.GenerarToken")
    @ResponseWrapper(localName = "generarTokenResponse", targetNamespace = "http://com/deceval/mrc/solicitud", className = "com.deceval.mrc.solicitud.GenerarTokenResponse")
    @WebResult(name = "return", targetNamespace = "http://com/deceval/mrc/solicitud")
    public com.deceval.mrc.solicitud.to.InformacionFirmaPagareTO generarToken(
        @WebParam(name = "informacionPagareTO", targetNamespace = "http://com/deceval/mrc/solicitud")
        com.deceval.mrc.solicitud.to.InformacionPagareTO informacionPagareTO
    );
}
