
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.deceval.mrc.solicitud;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.0.10
 * 2017-09-19T12:17:56.632-05:00
 * Generated source version: 3.0.10
 * 
 */

@javax.jws.WebService(
                      serviceName = "WsGenerarTokenService",
                      portName = "WsGenerarTokenPortTypePort",
                      targetNamespace = "http://com/deceval/mrc/solicitud",
                      wsdlLocation = "file:/D:/WORKSPACES/DECEVAL/WSCLIENTES/ClientSWSPagares/WebContent/WEB-INF/wsdl/WsGenerarTokenService.wsdl",
                      endpointInterface = "com.deceval.mrc.solicitud.WsGenerarTokenPortType")
                      
public class WsGenerarTokenPortTypePortImpl implements WsGenerarTokenPortType {

    private static final Logger LOG = Logger.getLogger(WsGenerarTokenPortTypePortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.deceval.mrc.solicitud.WsGenerarTokenPortType#generarToken(java.com_deceval_mrc_solicitud.InformacionPagareTO informacionPagareTO)*
     */
    public com.deceval.mrc.solicitud.to.InformacionFirmaPagareTO generarToken(com.deceval.mrc.solicitud.to.InformacionPagareTO informacionPagareTO) { 
        LOG.info("Executing operation generarToken");
        System.out.println(informacionPagareTO);
        try {
            com.deceval.mrc.solicitud.to.InformacionFirmaPagareTO _return = new com.deceval.mrc.solicitud.to.InformacionFirmaPagareTO();
            _return.setCodigoError("CodigoError-134217292");
            _return.setDescripcionError("DescripcionError666020641");
            _return.setUrlFirmaPagare("UrlFirmaPagare-2093587306");
            _return.setToken("Token179591985");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
